package com.lankaice.project.bo;

public enum BOType {
    ATTENDANCE,
    BILLING,
    BOOKING,
    CUSTOMER,
    DELIVERY,
    EMPLOYEE,
    INVENTORY_CART,
    ORDER_DETAIL,
    ORDER_PAYMENT,
    ORDERS,
    PENDING_ORDERS,
    PRODUCT,
    RAW_MATERIAL,
    SALARY,
    SALARY_PAYMENT,
    SMS_EMAIL,
    STOCK,
    SUPPLIER,
    TRANSPORT,
    USER,
    VEHICLE,
}
